name: Node.js CI Workflow

on:
  # Run workflow on push and pull request events for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Specify the version of Node.js
          cache: 'npm'

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: npm install

      # Step 4: Lint the code (if you have a linting script in package.json)
      - name: Run Linter
        run: |
          if [ -f package.json ]; then
            npm run lint || echo "No linter configured"
          fi

      # Step 5: Run Tests (if you have a testing script in package.json)
      - name: Run Tests
        run: |
          if [ -f package.json ]; then
            npm test || echo "No tests configured"
          fi

      # Step 6: Start the Application
      - name: Start Application
        run: |
          if [ -f package.json ]; then
            node src/index.js &
            sleep 5
          fi
